# Generated by Django 3.0 on 2020-10-21 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AffiliateUser',
            fields=[
                ('af_user_id', models.AutoField(primary_key=True, serialize=False)),
                ('af_user_name', models.CharField(max_length=100)),
                ('af_user_email', models.CharField(max_length=75, unique=True)),
                ('af_user_phone', models.CharField(max_length=14, unique=True)),
                ('af_user_address', models.CharField(blank=True, max_length=200)),
                ('af_user_password', models.CharField(max_length=64)),
                ('af_user_Gendar', models.CharField(blank=True, max_length=20, null=True)),
                ('af_user_photo', models.ImageField(upload_to='user/%Y/%d/%b')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=50, unique=True)),
                ('brand_code', models.PositiveSmallIntegerField(unique=True)),
                ('brand_short_description', models.CharField(blank=True, max_length=100)),
                ('brand_address', models.CharField(blank=True, max_length=100)),
                ('brand_logo', models.ImageField(upload_to='Brand/%Y/%d/%b')),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('catagory_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory_name', models.CharField(max_length=30, unique=True)),
                ('catagory_image', models.ImageField(upload_to='category/%Y/%d/%b')),
            ],
        ),
        migrations.CreateModel(
            name='CatagoryManager',
            fields=[
                ('catagory_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('catagory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='ColorSizeManager',
            fields=[
                ('color_size_manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('cupon_id', models.AutoField(primary_key=True, serialize=False)),
                ('cupon_name', models.CharField(blank=True, max_length=100)),
                ('cupon_code', models.CharField(max_length=50)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EcomUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
                ('user_email', models.CharField(max_length=75, unique=True)),
                ('user_phone', models.CharField(max_length=14, unique=True)),
                ('user_address', models.CharField(blank=True, max_length=200)),
                ('user_password', models.CharField(max_length=64)),
                ('user_Gendar', models.CharField(blank=True, max_length=20, null=True)),
                ('user_photo', models.ImageField(blank=True, null=True, upload_to='user/%Y/%d/%b')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('gift_card_id', models.AutoField(primary_key=True, serialize=False)),
                ('gift_card_name', models.TextField(max_length=500)),
                ('gift_card_number', models.TextField(max_length=500)),
                ('gift_card_pin', models.TextField(max_length=500)),
                ('gift_card_exp_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_name', models.CharField(blank=True, max_length=20)),
                ('offer_amount', models.FloatField(max_length=True)),
                ('offer_image', models.ImageField(upload_to='media/offer/%Y/%d/%b')),
                ('is_active', models.BooleanField(default=True)),
                ('offer_reason', models.CharField(blank=True, max_length=50)),
                ('start_time_date', models.DateTimeField(auto_now_add=True)),
                ('end_time_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfferMaxAmount',
            fields=[
                ('offer_max_amount_id', models.AutoField(primary_key=True, serialize=False)),
                ('max_amount', models.FloatField(max_length=20)),
                ('min_amount', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OfferType',
            fields=[
                ('offer_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('offer_type_name', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('fullorder_total_ammount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('delivery_date', models.DateTimeField()),
                ('af_user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reseller', to='RS69Eapp.AffiliateUser')),
                ('cupon_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Cupon')),
                ('offer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Offer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('order_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_status_name', models.CharField(default='', max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_method_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(blank=True, max_length=50)),
                ('payment_method_account_number', models.FloatField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(blank=True, max_length=50)),
                ('slug', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('product_info', models.TextField()),
                ('product_video', models.URLField(blank=True, null=True)),
                ('product_keyword', models.TextField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('product_description', models.CharField(blank=True, max_length=150)),
                ('product_image', models.ImageField(upload_to='product/%Y/%d/%b')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Brand')),
                ('catagory_manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.CatagoryManager')),
                ('color_and_size_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.ColorSizeManager')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('color_id', models.AutoField(primary_key=True, serialize=False)),
                ('color_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('product_price_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField(max_length=20)),
                ('product_price_entry_date', models.DateTimeField(auto_now_add=True)),
                ('offer_price', models.FloatField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('size_id', models.AutoField(primary_key=True, serialize=False)),
                ('size_val', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('report_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_title', models.TextField(max_length=500)),
                ('review', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SecurityInfo',
            fields=[
                ('security_info_id', models.AutoField(primary_key=True, serialize=False)),
                ('visitor_ip', models.CharField(max_length=25)),
                ('last_visit', models.DateTimeField(auto_now_add=True)),
                ('compromise_url', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingCost',
            fields=[
                ('shipping_cost_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_city', models.CharField(max_length=255)),
                ('shipping_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('slider_id', models.AutoField(primary_key=True, serialize=False)),
                ('slider_title', models.CharField(max_length=255)),
                ('slider_keyword', models.CharField(max_length=255)),
                ('slider_content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('slider_img', models.ImageField(upload_to='slider/%Y/%d/%b')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('store_name', models.CharField(max_length=255, unique=True)),
                ('store_address', models.TextField()),
                ('store_image', models.ImageField(upload_to='store/%Y/%d/%b')),
                ('store_email', models.CharField(max_length=50, unique=True)),
                ('store_phone', models.CharField(max_length=20, unique=True)),
                ('store_password', models.CharField(max_length=64)),
                ('store_licence', models.CharField(blank=True, max_length=100, null=True)),
                ('store_nid', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('wishlist_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.EcomUser')),
            ],
        ),
        migrations.CreateModel(
            name='UserConfirmation',
            fields=[
                ('user_confirmation_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_confirmation_code_numbere', models.PositiveSmallIntegerField(unique=True)),
                ('validation_start_datetime', models.DateTimeField(auto_now_add=True)),
                ('validation_end_datetime', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.EcomUser')),
            ],
        ),
        migrations.CreateModel(
            name='SubCatagory',
            fields=[
                ('sub_catagory_id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_catagory_name', models.CharField(blank=True, max_length=50)),
                ('catagory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Catagory')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('shipping_id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_address', models.CharField(blank=True, max_length=150)),
                ('city_name', models.CharField(blank=True, max_length=20, null=True)),
                ('post_code', models.PositiveSmallIntegerField()),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.EcomUser')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewReplay',
            fields=[
                ('review_replay_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_replay_title', models.TextField(max_length=500)),
                ('review_replay', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('review_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Review')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('report_comment', models.TextField()),
                ('report_time', models.DateTimeField(auto_now_add=True)),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.ReportType')),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Store')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.EcomUser')),
            ],
        ),
        migrations.CreateModel(
            name='ProductGalary',
            fields=[
                ('pro_gal_id', models.AutoField(primary_key=True, serialize=False)),
                ('Image', models.ImageField(upload_to='media/product/%Y/%d/%b')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='RS69Eapp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_price_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.ProductPrice'),
        ),
        migrations.AddField(
            model_name='product',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Store'),
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('order_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('cupon_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Cupon')),
                ('offer_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Offer')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='RS69Eapp.Order')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_status_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.OrderStatus'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer', to='RS69Eapp.EcomUser'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_max_amount_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.OfferMaxAmount'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.OfferType'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Order')),
                ('payment_method_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='RS69Eapp.Payment')),
            ],
        ),
        migrations.AddField(
            model_name='cupon',
            name='offer_max_amount_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.OfferMaxAmount'),
        ),
        migrations.AddField(
            model_name='colorsizemanager',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.ProductColor'),
        ),
        migrations.AddField(
            model_name='colorsizemanager',
            name='size_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.ProductSize'),
        ),
        migrations.AddField(
            model_name='catagorymanager',
            name='sub_catagory_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.SubCatagory'),
        ),
    ]
