# Generated by Django 3.0 on 2020-10-30 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RS69Eapp', '0002_auto_20201021_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTrafficIp',
            fields=[
                ('ip_id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=50, unique=True)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('count', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RS69Eapp.Product')),
            ],
        ),
    ]
